//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUES
    {
        public int CHECODIGO { get; set; }
        public Nullable<int> PEDCODIGO { get; set; }
        public string NOMECLIENTE { get; set; }
        public string NOMEDOCHEQUE { get; set; }
        public Nullable<decimal> CHEVALOR { get; set; }
        public Nullable<System.DateTime> CHEDATADEPOSITO { get; set; }
        public string CHESITUACAO { get; set; }
        public string CHETELEFONE { get; set; }
        public string CHECELULAR { get; set; }
        public string CHEOBS { get; set; }
        public Nullable<System.DateTime> CHEDATA { get; set; }
        public string CPFDOCHEQUE { get; set; }
        public string CHEBANCO { get; set; }
        public string CHENUMERO { get; set; }
        public string CHECONTACORRENTE { get; set; }
        public string CHEAGENCIA { get; set; }
        public string ULTIMOACESSO { get; set; }
        public Nullable<System.DateTime> ULTIMOACESSODATA { get; set; }
        public string CHECNPJ { get; set; }
    }
}
