//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFSISTEMA
    {
        public int CODG { get; set; }
        public string URLIMPRESSORA { get; set; }
        public string URLORC { get; set; }
        public string URLPEDIDO { get; set; }
        public string SENHAEXCLUSAO { get; set; }
        public string SENHAALTERAR { get; set; }
        public Nullable<System.DateTime> DATAEXPIRACAO { get; set; }
        public Nullable<int> STATUSBLOQUEIO { get; set; }
        public string URLPESQUISA { get; set; }
        public string URLCPF { get; set; }
        public string URLCNPJ { get; set; }
        public string EUSUARIO { get; set; }
        public string ESENHA { get; set; }
        public string EAUTENTICAREQUERIDA { get; set; }
        public string EUTILIZASSL { get; set; }
        public string EENDERECOSMTP { get; set; }
        public string EPORTASMTP { get; set; }
        public string EREMETENTE { get; set; }
        public string URLNOTA { get; set; }
    }
}
