//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        public int FORCODG { get; set; }
        public string FORNOME { get; set; }
        public string FORCNPJ { get; set; }
        public string FORENDERECO { get; set; }
        public string FORBAIRRO { get; set; }
        public string FORCIDADE { get; set; }
        public string FORRAMO { get; set; }
        public string FORCONTATO { get; set; }
        public string FOROBS { get; set; }
        public string FORGRUPOPRODUTO { get; set; }
        public string FORTELEFONE { get; set; }
        public string FORCELULAR { get; set; }
        public string FORFAX { get; set; }
        public string FOREMAIL { get; set; }
        public string FORCEP { get; set; }
    }
}
