//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIOS
    {
        public int CODG { get; set; }
        public string FUNCIONARIO { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string ENDERECO { get; set; }
        public string PONTOREF { get; set; }
        public string CEP { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATACAD { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
        public Nullable<decimal> INSS { get; set; }
        public Nullable<decimal> VALETRANSP { get; set; }
        public Nullable<decimal> VALEREFEICAO { get; set; }
        public Nullable<decimal> VALORLIQUIDO { get; set; }
        public string OBS { get; set; }
    }
}
