//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMGENDERECO
    {
        public int CODG { get; set; }
        public Nullable<int> CLICODIGO { get; set; }
        public byte[] IMAGEM { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
        public Nullable<System.DateTime> DATAALTERACAO { get; set; }
        public string USUARIOALTERACAO { get; set; }
        public string USUARIOCRIACAO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
