//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENSORCAMENTOS
    {
        public int IOCODIGO { get; set; }
        public Nullable<int> ORCCODIGO { get; set; }
        public Nullable<int> PROCODIGO { get; set; }
        public Nullable<int> IOQUANTIDADE { get; set; }
        public Nullable<decimal> IOPRECOUNITARIO { get; set; }
        public Nullable<decimal> IOTOTAL { get; set; }
        public Nullable<decimal> IOPRECOREPOSICAO { get; set; }
        public Nullable<decimal> IOTOTALREPOSICAO { get; set; }
    }
}
