//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGNF
    {
        public int LOGNFCODG { get; set; }
        public Nullable<int> LOGNFCODIGO { get; set; }
        public Nullable<int> LOGNFCLICODIGO { get; set; }
        public Nullable<System.DateTime> LOGNFTIME { get; set; }
        public string LOGNFUSUARIO { get; set; }
        public string LOGNFOPERACAO { get; set; }
    }
}
