//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGPEDIDOS
    {
        public int LOGPCODIGOPED { get; set; }
        public Nullable<int> LOGPEDIDO { get; set; }
        public string LOGPDESCRICAO { get; set; }
        public string LOGPUSUARIO { get; set; }
        public Nullable<System.DateTime> LOGPTIME { get; set; }
        public string LOGPOPERACAO { get; set; }
    }
}
