//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NF
    {
        public int CODIGO { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<System.DateTime> DATAIMPRESSAO { get; set; }
        public string OBS { get; set; }
        public string DESCRICAO { get; set; }
        public string SITUACAO { get; set; }
        public string ULTIMOACESSO { get; set; }
        public Nullable<System.DateTime> ULTIMOACESSODATA { get; set; }
        public string EMITIDOPOR { get; set; }
        public Nullable<System.DateTime> EMITIDOPORDATA { get; set; }
        public string OBS2 { get; set; }
        public string ULTIMOIMPRESSAO { get; set; }
        public int NFCLICODIGO { get; set; }
        public Nullable<System.DateTime> DATAAGENDA { get; set; }
    }
}
