//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public int PEDCODIGO { get; set; }
        public Nullable<int> ORCCODIGO { get; set; }
        public Nullable<System.DateTime> PEDDATAEMISSAO { get; set; }
        public Nullable<System.DateTime> PEDDATALOCACAO { get; set; }
        public Nullable<System.DateTime> PEDDATASAIDA { get; set; }
        public Nullable<System.DateTime> PEDDATADEVOLUCAO { get; set; }
        public int CLICODIGO { get; set; }
        public Nullable<int> FORCODIGO { get; set; }
        public byte[] PEDOBS { get; set; }
        public Nullable<decimal> PEDDIARIA { get; set; }
        public byte[] PEDOBS2 { get; set; }
        public string PEDTIPOENTREGA { get; set; }
        public string PEDATENDENTE { get; set; }
        public Nullable<decimal> PEDVALORPAGO { get; set; }
        public Nullable<decimal> PEDDESCONTO { get; set; }
        public Nullable<int> PEDSTATUS { get; set; }
        public string PEDSTATUSPGTO { get; set; }
        public Nullable<System.DateTime> DATAIMPRESSAO { get; set; }
        public string ULTIMOACESSO { get; set; }
        public Nullable<System.DateTime> ULTIMOACESSODATA { get; set; }
        public string EMITIDOPOR { get; set; }
        public Nullable<System.DateTime> EMITIDOPORDATA { get; set; }
        public string ULTIMOIMPRESSAO { get; set; }
        public Nullable<decimal> PEDDESCONTOP { get; set; }
    }
}
