//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public int PROCODIGO { get; set; }
        public Nullable<int> GRUCODIGO { get; set; }
        public Nullable<int> SUBGCODIGO { get; set; }
        public string PRODESCRICAO { get; set; }
        public Nullable<decimal> PROPRECOUNITARIO { get; set; }
        public Nullable<decimal> PROREPOSICAO { get; set; }
        public string PROUNIDADE { get; set; }
        public Nullable<int> PROESTOQUE { get; set; }
        public string ULTIMOACESSO { get; set; }
        public Nullable<System.DateTime> ULTIMOACESSODATA { get; set; }
        public string EMITIDOPOR { get; set; }
        public Nullable<System.DateTime> EMITIDOPORDATA { get; set; }
    }
}
