//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBGRUPOPRODUTOS
    {
        public int SUBGCODIGO { get; set; }
        public string SUBGDESCRICAO { get; set; }
    }
}
