//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CODG { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string PERFIL { get; set; }
    }
}
